application: reddeshop
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  
- url: /static
  static_dir: static
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /admin.*
  script: admin.app
  
- url: /payment.*
  script: payment.app

- url: .*
  script: user.app

libraries:
- name: jinja2
  version: latest