application: reddeshop
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /css
  static_dir: css

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest